 [[gestures]]
 num_fingers = 3
 kind = "SwipeDown"
 action = "notify-send 'Three Finger Swipe Down'"
 min_duration = 50
 mix_distance = 100.0

[[gestures]]
num_fingers = 2
kind = "SwipeLeft"
action = "notify-send 'Two Finger Swipe Left' (Right Edge)"
min_duration = 50
min_distance = 100.0
on_edge = { Right = 300 }

[[gestures]]
num_fingers = 2
kind = "SwipeRight"
action = "notify-send 'Two Finger Swipe Right' (Left Edge)"
min_duration = 50
min_distance = 100.0
on_edge = { Left = 300 }

[[gestures]]
num_fingers = 2
kind = "SwipeDown"
action = "notify-send 'Two Finger Swipe Down (Left Edge)'"
min_duration = 50
min_distance = 100.0
on_edge = { Left = 300 }

[[gestures]]
num_fingers = 2
kind = "SwipeDown"
action = "notify-send 'Two Finger Swipe Down (Top Edge)'"
min_duration = 50
min_distance = 100.0
on_edge = { Top = 300 }

[[gestures]]
num_fingers = 2
kind = "SwipeUp"
action = "notify-send 'Two Finger Swipe Up (Bottom Edge)'"
min_duration = 50
min_distance = 100.0
on_edge = { Bottom = 300 }

[[gestures]]
num_fingers = 4
kind = "Press"
action = "notify-send 'Long Press' 'Four finger long press detected'"
min_duration = 500
max_distance = 20.0
